version: '3.5'

services:

  postgresql:
    build:
      context: ./postgres
    environment:
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_USER=jiradb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
      - "LANG=C"

  jira:
    build:
      context: ./jira
    depends_on:
      - postgresql
    ports:
      - '2990:8080'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql/jiradb'
      - 'ATL_JDBC_USER=jiradb'
      - 'ATL_JDBC_PASSWORD=password'
      - 'ATL_DB_DRIVER=org.postgresql.Driver'
      - 'ATL_DB_TYPE=postgres72'
      - 'ATL_TOMCAT_CONTEXTPATH=/jira'
      - 'JVM_SUPPORT_RECOMMENDED_ARGS=-Dspring.profiles.active=allowAnyTransition'
    command: >
      bash -c '
          waitport postgresql 5432 &&
          chown -R jira.jira  /var/atlassian/application-data/jira/ &&
          /entrypoint.py
      '

  cypress:
    build:
      context: ./cypress
    environment:
      - CYPRESS_AWS_ACCESS_KEY_ID=${CYPRESS_AWS_ACCESS_KEY_ID}
      - CYPRESS_AWS_SECRET_ACCESS_KEY=${CYPRESS_AWS_SECRET_ACCESS_KEY}
    command: >
      bash -c '
          cd /opt/cypress &&
          yarn install &&
          jira-wait http://jira:8080/jira/ &&
          yarn test --spec integration/smoketest.ts
      '
