#!/bin/bash -x

JAR_FILE=$(ls ./jira-plugin/target/jira-plugin-*.jar | head -n1)
JAR_FILE_NAME=$(basename "$JAR_FILE")
echo "Using jar file - $JAR_FILE"

jsrc="jira-plugin/target/$JAR_FILE_NAME"
jtarget="jira-e2e-tests/jira/$JAR_FILE_NAME"

if [[ $jsrc -nt $jtarget ]]; then
    cp $jsrc $jtarget
fi


source .env
for arg do
  shift
  if [[ "$arg" == "--allowAnyTransition" ]]; then
      JVM_SUPPORT_RECOMMENDED_ARGS="-Dspring.profiles.active=allowAnyTransition ${JVM_SUPPORT_RECOMMENDED_ARGS}"
      continue
  fi
  set -- "$@" "$arg"
done
export JVM_SUPPORT_RECOMMENDED_ARGS

cd jira-e2e-tests/
./postgres/inject-license

docker-compose rm -sf
docker-compose up --force-recreate --build jira postgresql $@
