# Snyk security scan to be run everyday at midnight.
#
# As of 03/05/2022 there are no severe security issues
# associated with master, other than those which have exemptions
# defined in the respective module .snyk files. 
#
# If there are severe issues encountered on master this action 
# will fail and cause the build to go red until the security issue 
# is remediated. 

name: Security scan - daily on main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --exclude=templates --severity-threshold=high --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
