# Snyk on branch security scanning

name: On branch Snyk security scan

on:
  push:
    branches-ignore:
      - master
        
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --exclude=templates --sarif-file-output=snyk.sarif
      - name: Print the content for the snyk.sarif file
        if: ${{ always() }}
        run: |
          cat snyk.sarif
      - name: Upload result to GitHub Code Scanning
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
